/**
 * Codex app-server protocol types, GENERATED by `codex app-server generate-ts`
 * (codex-cli 0.144.4 — regenerate on CLI version bumps, never hand-edit; see
 * README.md and docs/PROTOCOL_NOTES.md). Everything in ./generated is emitted
 * verbatim by the CLI; this file is the only hand-written entry point.
 *
 * Import via the `@eduagent/shared/protocol` subpath — these types are NOT
 * re-exported from the package root, because no module outside
 * `apps/server/src/codex/` may depend on protocol shapes (plans/03 §2).
 */
export * from './generated/index';
