/**
 * Deterministic PRNG for the demo seeder (plans/02 §7: "generated by a
 * deterministic script"). Mulberry32 — tiny, seedable, plenty for varying
 * phrasing and cadence. Never use Math.random() in the seeder.
 */

export type Rng = () => number;

export function mulberry32(seed: number): Rng {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Integer in [min, max] inclusive. */
export function randInt(rng: Rng, min: number, max: number): number {
  return min + Math.floor(rng() * (max - min + 1));
}

/** Uniform pick. */
export function pick<T>(rng: Rng, items: readonly T[]): T {
  if (items.length === 0) throw new Error('pick from empty list');
  return items[Math.floor(rng() * items.length)]!;
}

/**
 * Picks from a phrase bank while avoiding the most recently used entries —
 * the cheap trick that keeps 140 commits from repeating the same three
 * sentences back to back (the "machine-generated tell" the demo review
 * explicitly screens for).
 */
export class VariedPicker {
  private recent: string[] = [];
  constructor(
    private readonly rng: Rng,
    private readonly memory = 4,
  ) {}

  pick(bank: readonly string[]): string {
    const fresh = bank.filter((item) => !this.recent.includes(item));
    const choice = pick(this.rng, fresh.length > 0 ? fresh : bank);
    this.recent.push(choice);
    if (this.recent.length > this.memory) this.recent.shift();
    return choice;
  }
}
